### PR TITLE
Add is-empty helper

### PR DESCRIPTION
**Pull request by drewclauson**
I'm pretty new at testing with Ember, so go easy on me. :smile:   Let me know if you want any tests added, etc.  I have this working in a project.

Thanks!

### CODE REVIEW

**Comment by jmurphyau** [comment]
I'm sort of against adding array related helpers - I would think these should exist in a new addon to keep this one small and focused.. Don't want to have to track arrays and changes to arrays

**Comment by rwjblue** [comment]
Yeah, I agree, however this isn't array related AFAICT.  It is using `Ember.isEmpty(params[0])` which is doing:

> Verifies that a value is null or an empty string, empty array, or empty function.

Per http://emberjs.com/api/#method_isEmpty.

---

I kinda agree that I would expect `is-empty` to deal with arrays (this is what I initially thought from the PR title also).

**Comment by drewclauson** [comment]
Haha, I didn't have arrays in mind at all. I just need to show / hide properties on a template and want to avoid something verbose like this:

` if(or( not-eq model.field '') (not-eq model.field null))’

However you could argue that the above statement should really be a computed property anyways...

No worries if you'd rather not include it. If nothing else it was a good exercise for me to get my feet wet in testing!

**Comment by jmurphyau** [comment]
I dunno what happened between me posting my comment and now but I clearly missed the comments from you guys..

Can you add some tests around arrays for me?

1: Initial array not empty, remove objects making it empty 
2: Initial array empty, add objects making it not empty

Ember.isEmpty might handle it but whether the helper execution gets retriggered when items are added or removed I'm not too sure - it's been a while since I touched any ember code sadly :(

**Comment by jmurphyau** [comment]
We have an Ember.isArray helper and since this is another Ember.isXXX related helper it leans me away from my original comments slightly.. It's strange because it's almost a mix between being an array related helper (requiring access to elements inside an array) and not.. This is a interesting one :)

I'm thinking about what the next update in this library should include.. Before adding any more helpers I want the ability to allow users to exclude/include.. That coupled with adding a set of Ember.isXXX helpers that are by default excluded I think would be a good update

**Comment by devinus** [comment]
I have to add an `is-empty` helper to all my Ember projects that proxies to Ember.isEmpty. It feels natural that it would be in this project. Is there no chance of seeing it anytime soon?

**Comment by jmurphyau** [comment]
Do you want to rebase this? And also add the following tests:

1: Initial array not empty, remove objects making it empty
2: Initial array empty, add objects making it not empty
3: A string with a single space in it

I've failed very behind in being involve in Ember related things its a bit slack. I'm keen on adding this in

**Comment by drewclauson** [comment]
Unfortunately, I got reassigned off Ember so I haven't developed in it for a year. 👎 👎   I don't have enough knowledge of the new stuff right now to do it justice

**Comment by rwjblue** [comment]
@drewclauson - Thanks for your work on this!  Closing this PR for now, since you mentioned you wouldn't have time to complete...

**Pull request closed without merging**
