### PR TITLE
Add is-none helper

### LINKED ISSUE #79: Add is-none helper
...that proxies the Ember function of the same name (it's useful to distinguish between null/undefined values and empty strings)

I'm using this in a project; hopefully find time to pull it out, add the needed tests and docs, and submit a PR soon

### PR DESCRIPTION
**Pull request by rwwagner90**
Closes #79

### CODE REVIEW

**Comment by rwwagner90** [comment]
@jmurphyau @rwjblue thoughts on adding this?

**Comment by rwwagner90** [comment]
@jmurphyau @rwjblue if this is not desired, I will close the PR.

**Comment by jmurphyau** [comment]
Hi

Sorry about not responding.. I don't really have a job where I do web development anymore so trying to find time to care for this repo is difficult.. I'll see if I can find some this week.. Without looking at anything else (ie any other issues or PRs or knowing really whats going on with the rest of the repo), this does seem like a good addition though.

**Comment by rwwagner90** [comment]
@jmurphyau no worries! Would you perhaps be interested in transferring this addon to https://github.com/adopted-ember-addons?

**Comment by rwwagner90** [comment]
@jmurphyau thoughts on transferring or at least perhaps adding me as a maintainer here? There are lots of updates that could be made.

**Comment by rwwagner90** [comment]
Closing since there seems to be no interest.

**Pull request closed without merging**
