### PR TITLE
Remove file extensions from import paths

### PR DESCRIPTION
**Pull request by owzzz**
In trying out the `4.0.0-beta.0` release I noticed eslint was complaining about the file extension being used on the import path.

The error was:

```
node_modules/ember-truth-helpers/declarations/template-registry.d.ts(13,37): error TS2691: An import path cannot end with a '.ts' extension. Consider importing './helpers/xor.js' instead
```

This PR removes  the file extensions completely where applicable.

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@owzzz interesting, why would this to do anything with ESLint in your app? Note that .ts extension was added deliberately, for some more info see https://github.com/embroider-build/addon-blueprint/pull/160

**Comment by locks** [comment]
CI is _not_ happy 😬

**Comment by SergeAstapov** [comment]
TBH I think this is wrong thing to change as .ts extension only affects authoring format (required by rollup) and should not affect publishing format.

@owzzz may I ask you to create a simple repro repository so I can dig into the problem?

**Comment by NullVoxPopuli** [comment]
Hey, @owzzz were you able to get ESLint to ignore your `node_modules`?

**Comment by SergeAstapov** [comment]
we have v4.0.0 out and believe this is not an issue with addon but rather an issue with ESLint on this particular case which should not lint `node_modules` folder

**Pull request closed without merging**
