### PR TITLE
Add in-array helper

### PR DESCRIPTION
**Pull request by gannetson**
To check if a value/object exists in an array.

### CODE REVIEW

**Comment by jmurphyau** [comment]
Unfortunately this won't work.. If you're viewing a template and items are added to the array the helper does not update..

This could be done with the new helpers in Glimmer but not before that

**Comment by gannetson** [comment]
It does work for me as a simple helper:
https://github.com/gannetson/fogg_client/blob/master/app/helpers/in-array.js
and
https://github.com/gannetson/fogg_client/blob/master/app/templates/user.hbs#L8

**Comment by Kilowhisky** [comment]
Here's my implementation that properly observes array changes. Don't know if this will help


```
/**
 * This helper checks to see if a value is present in the array.
 *
 * @example {{#if (in-array indexArray indexToCheck)}} .... {{/if}}
 * @see http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_new-ember-js-helper-api
 */
export default Ember.Helper.extend({

    /**
     * The array that was passed in that needs to be observed
     * for changes so that it can be recomputed.
     */
    array: null,

    /**
     * Actually performs the computation.
     */
    compute: function(params /*, hash*/){
        // Validate
        if(!Array.isArray(params[0]) || params.length !== 2){
            return false;
        }

        // Setup the observer only if the array is different
        if(this.get('array') !== params[0]){
            this.set('array', params[0]);
        }

        // Return
        return params[0].indexOf(params[1]) !== -1;
    },
    arrayChange: Ember.observer('array.[]', function(){
        this.recompute();
    }),
});
```

**Comment by rwjblue** [comment]
@Kilowhisky's version seems more correct to me.  I'm going to close this for now, but I'd happily review a PR with that approach.

**Pull request closed without merging**
