### PR TITLE
Upgraded ember-cli => v2.15.0-beta.2

### PR DESCRIPTION
**Pull request by toranb**
Similar to #63 but I went ahead and pushed to the very latest ember-cli/ ember source

### CODE REVIEW

**Comment by toranb** [comment]
screen shot 2017-08-11 at 10 01 09 pm

What is the best option for this ^^ ? anyone seen it before?

**Comment by rwjblue** [comment]
was an issue with a release of fast-sourcemap-concat, @ef4 fixed it and released an update

**Comment by rwjblue** [comment]
I cleared the CI cache and restarted the failed jobs.

**Comment by toranb** [comment]
@rwjblue u the boss :) thanks dude

**Comment by toranb** [comment]
@rwjblue done and done :)

**Comment by rwjblue** [comment]
Thank you @toranb!

**Pull request merged**
