### PR TITLE
Update structure ember-addon (2.12)

### PR DESCRIPTION
**Pull request by aureliosaraiva**
This Pull Request modify the structure the ember-addon for latest version.

### CODE REVIEW

**Comment by aureliosaraiva** [comment]
@rwjblue  can you review it?

**Comment by jmurphyau** [comment]
I'll take a look in a few hours

**Comment by aureliosaraiva** [comment]
@jmurphyau updated!

**Comment by aureliosaraiva** [comment]
@jmurphyau Do you can rebuild Travis?

This was job cancel.

https://travis-ci.org/jmurphyau/ember-truth-helpers/builds/261111148?utm_source=github_status&utm_medium=notification

**Comment by jmurphyau** [comment]
It looks to all pass

Do you mind squashing it into one commit?

**Comment by aureliosaraiva** [comment]
I did merge with master and now I can't squashing. :confused:

**Comment by aureliosaraiva** [comment]
Close in favor: https://github.com/jmurphyau/ember-truth-helpers/pull/63

**Pull request closed without merging**
