### PR TITLE
xor helper

### PR DESCRIPTION
**Pull request by Keeo**
What do you think about xor helper?

### CODE REVIEW

**Comment by Keeo** [comment]
friendly ping @jmurphyau

**Comment by rwjblue** [comment]
@Keeo - Looks great!  Thanks for taking the time to submit!

**Comment by rwjblue** [comment]
@jmurphyau - Mind releasing for this?

**Comment by jmurphyau** [comment]
Yep - I'll push out a new version today.. 

Thanks @Keeo and @rwjblue!

**Comment by Keeo** [comment]
cool thanks

**Pull request merged**
