### PR TITLE
updated addon (2.14)

### PR DESCRIPTION
**Pull request by aureliosaraiva**
https://github.com/jmurphyau/ember-truth-helpers/pull/54

### CODE REVIEW

**Comment by aureliosaraiva** [comment]
@jmurphyau sorry, by last PR. All resolved now.

**Comment by rwjblue** [comment]
Thank you very much for all of your hard work here! I'm terribly sorry I merged the update in #64 instead. :(

**Comment by toranb** [comment]
@aureliosaraiva its my fault - I did that ember-cli 2.15.0-beta 2 update without first looking at the open PRs :(

**Comment by aureliosaraiva** [comment]
@toranb @rwjblue No prob!

**Pull request closed without merging**
